### ISSUE TITLE
Magnets freezes with 3x3 Tricky

### ISSUE THREAD

**Issue by TZornG** [SteffenBauer/PocketPuzzles#17]
Hi Steffen,

I was playing around with the custom set-up of Magnets. I found when you try to create a game with 3x3 grid size and tricky difficulty the game freezes. The strip-clue option does not have an impact.

I also have the feeling that the battery gets drained when the app hangs. Could it be the app keeps trying to create a puzzle without time-out?

**Comment by SteffenBauer** [comment]
Hi, thanks for finding this bug. I can reproduce this via the local desktop version of *magnets*. The generation algorithm is indeed hanging in an endless loop for a 3x3 configuration at tricky level. Interestingly, also for 4x4 and even 4x5 tricky puzzles.

This also explains battery drain when the app freezes that way. Unfortunately, introducing a timeout is not trivial. The original SGT puzzles are designed to stay completely inside the generation loop without returning until a puzzle is successfully generated. Best way to solve this would be to move game generation to a separate thread, but there I will need to find the time to code it.

For now, I think I will quickly solve this by introducing lower size requirements for tricky puzzles, so that generation of too small tricky puzzles will be rejected.

**Comment by SteffenBauer** [comment]
Quick-Fix by size limits implemented in https://github.com/SteffenBauer/PocketPuzzles/commit/146edd0bac97efa8c70c04eb074bd04e1735f7b1

4x5 tricky puzzles seem to be possible anyway, so I added according lower size limits to tricky puzzles.
You can try the nightly build at release/nightly , should solve this issue for now.

**Comment by TZornG** [comment]
Thanks for putting in the quick fix. Maybe you can still simplify it. Now you put in a series of checks on dimension level. I had to confirm the warning and change values 3 times after trying to start a 3x3 game. 3x3 -> 4x3 -> 4x4 -> 5x4.

The Android versions simply has one check/warning: "Either width or height must be at least five for Tricky".

**Comment by SteffenBauer** [comment]
Unfortunately, this one check seems not to be sufficient enough. When I try to generate a tricky 3x6 puzzle, the generator also hangs. I think it is safest to leave the current check as it is, as it ensures that a) both sides must be at least size 4 b) at least one side must be 5.
