### ISSUE TITLE
Installation notes

### ISSUE THREAD

**Issue by justaquestion** [SteffenBauer/PocketPuzzles#25]
The app works fine on Touch Lux 4. However, some installation notes could be useful. I am not sure that this is the best way: I copied the downloaded SGTPuzzles.app  binary to /system/bin. and added an SGTPuzzles.app bash file to /applications:
#!/bin/sh
exec /mnt/ext1/system/bin/SGTPuzzles.app

**Comment by SteffenBauer** [comment]
Hi, installation notes should actually be included since a long time, they can be found at both the release page:

https://github.com/SteffenBauer/PocketPuzzles/blob/master/release/README.md#installation

and at the manual build paragraph:

https://github.com/SteffenBauer/PocketPuzzles#manual-build

I'm not sure whether you just oversaw them, or if it is actually necessary on the Touch Lux 4 to install the app in `/system/bin`. Can you clarify this point?

The standard procedure is to copy the `SGTPuzzles.app` itself to `/applications`, nothing more.

**Comment by justaquestion** [comment]
> Hi, installation notes should actually be included since a long time, they can be found at both the release page:
> 
> https://github.com/SteffenBauer/PocketPuzzles/blob/master/release/README.md#installation
> 
> and at the manual build paragraph:
> 
> https://github.com/SteffenBauer/PocketPuzzles#manual-build
> 
> I'm not sure whether you just oversaw them, or if it is actually necessary on the Touch Lux 4 to install the app in `/system/bin`. Can you clarify this point?
> 
> The standard procedure is to copy the `SGTPuzzles.app` itself to `/applications`, nothing more.
No, it is not necessary, I indeed oversaw them. The latest firmware is 6.5 also for Touch Lux 4. It was just strange for me with respect to the general Linux directory structure to put a binary directly in /applications
