### ISSUE TITLE
Faster buttons

### ISSUE THREAD

**Issue by HasbersHz** [SteffenBauer/PocketPuzzles#30]
Mostly slow buttons not a problem, but this is get bad when you tries to change number of mines in minesweeper.

**Comment by SteffenBauer** [comment]
Hi, this is unfortunately not enough information to really understand what the problem is.

I guess you mean that short-clicks in Mines reveal a cell, and long-clicks mark a cell with a flag. And that re-marking cells with flags takes too long that way? Is my guess correct?

If so, fortunately there is already a solution: From v0.8.0, some games offer an additional configuration screen to configure the game UI behaviour. Mines offers exactly that: You can set whether short-click reveals a cell or sets a flag, and long-click the other way round.

You can find that option in Mines by clicking the checkerboard symbol on the top right, and click there on "Settings".

Should your question on the other hand ask to shorten the length for a long-click, then unfortunately there is no solution. The length of short and long clicks is given by he PocketBook operating system, and cannot be changed as far as I know.

Please check this and write here a short note if the first solution solved your issue.

**Comment by HasbersHz** [comment]
Oh, I really sorry. I mean changing mines in custom game preset.
Btw, i have 3 questions:
1. Can i make a translation?
2. Can i make a small patch to add hexadecimal view for numbers in games?
3. Is there going to be statistics?
I probably going to do 1 and 2 in fork. I am asking to add this to this repo.

**Comment by SteffenBauer** [comment]
Best make a fork so I can check the code and decide if and what I want to add it to my repository.
Closing this issue now.

**Comment by HasbersHz** [comment]
> Best make a fork so I can check the code and decide if and what I want to add it to my repository. Closing this issue now.

But this is still the issue... Okey, forget it.

**Comment by SteffenBauer** [comment]
There I need to ask again what the issue is and what change exactly you propose? Because it is still not clear to me what you issue exactly is.
Do you want that the default preferences in the game presets are changed?

**Comment by HasbersHz** [comment]
> There I need to ask again what the issue is and what change exactly you propose? Because it is still not clear to me what you issue exactly is. Do you want that the default preferences in the game presets are changed?

Sorry, i still didn't make it clear to you.
Changing amount of mines in "custom" "game presets" is slow and i think that this buttons can be speed up.

**Comment by SteffenBauer** [comment]
Added + - 5 buttons to the mines number in commit https://github.com/SteffenBauer/PocketPuzzles/commit/ebed4b5fa564e3e8a15feee20ce51a3f1bcd6918

Binary at https://github.com/SteffenBauer/PocketPuzzles/blob/master/release/nightly/SGTPuzzles.app

Please test and drop a note if this makes adjusting mines numbers more easy.

**Comment by HasbersHz** [comment]
> Please test and drop a note if this makes adjusting mines numbers more easy.

Yes, it's faster. I would prefer 10 over 5, but this is probably enough. And there is some games where big numbers too.
Examples that i have:
1. Untangle.
2. Sixteen with "Number of shuffling moves".
3. Map with "Regions"

**Comment by SteffenBauer** [comment]
> there is some games where big numbers too.
Good hint. I implemented a new parameter type `C_STRING_MORE` for this change, so should be very quick to modify these games too, by simply adjusting the according fields in `game_configure`.

**Comment by HasbersHz** [comment]
> > there is some games where big numbers too.
> I implemented a new parameter type

I saw. Just asking for games that i play.

**Comment by SteffenBauer** [comment]
Added according buttons to *map*, *sixteen* and *untangle*, and adjusted a little bit screen placing of the +-5 buttons.
